kind: pipeline
name: default

workspace:
  base: /book
  path: ops-curriculum

steps:
- name: build
  image: panbook:latest
  pull: if-not-exists
  commands:
  - panbook book --style=elegantbook -d

- name: build-mobile
  image: panbook:latest
  pull: if-not-exists
  commands:
  - panbook book -V device:mobile -d
 
- name: publish
  image: annprog/rsync:latest
  pull: if-not-exists
  settings:
    src: build/*.pdf
    dest: 172.17.0.1::panbook
  depends_on:
  - build
  - build-mobile